### ISSUE TITLE
Restrict Channel specific Welcome Bot message config to users who have permission to manage channels 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-welcomebot#41]
PR https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31 introduced slash commands to manage channel specific welcome bot messages. 
`set_channel_welcome`, `get_channel_welcome` and `delete_channel_welcome`

When an enterprise license is applied not all roles have the ability to manage channels. Therefore  these commands should only be available to Channel Admin roles.

**Comment by mickmister** [comment]
There's an abandoned PR for this here https://github.com/mattermost/mattermost-plugin-welcomebot/pull/78
