### ISSUE TITLE
Welcome channel message visibil for all channel members?

### ISSUE THREAD

**Issue by schlueter-de** [mattermost-community/mattermost-plugin-welcomebot#95]
Hi,

the welcome channel message is atm "(Only visible to you)". 

I want to make an automated channel welcome message for new userser that is visibil for all channel Members. If its like a channelmessage all useres could replay to the message an welcome the new member in our team. 

Is this possible? 

Regards

**Comment by Kshitij-Katiyar** [comment]
@mickmister @schlueter-de Sometimes the welcome message also contains some action items (Buttons) to add new users to different teams. If we show that msg to everyone then anyone can interact with it. Moreover, a msg does get posted whenever a person gets added to a channel. And if we want to implement this then we can add a plugin config setting to send msg either as a ephermal post or a normal one.

**Comment by mickmister** [comment]
@Kshitij-Katiyar I think this feature is out of scope for this plugin. AFAIK it's only meant for private user interactions. Thoughts on closing this?

**Comment by Kshitij-Katiyar** [comment]
sure @mickmister Closing the issue as it is out of scope for now.
